FROM mhart/alpine-node

WORKDIR /src
ADD . .

# for native dependencies, and extra tools
# RUN apk add --no-cache make gcc g++ python
RUN apk add --no-cache git

RUN npm install

EXPOSE 3000 5858
CMD ["./node_modules/.bin/nodemon", "--debug","app.js"]